name: oer-environment
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - internetarchive
    - matplotlib
    - nltk
    - pandas
    - pillow
    - pyspellchecker
    - pytesseract
    - requests
